[tools]
python = "3.11"
uv = "latest"

[tasks.test]
run = "uv run pytest"

[tasks.'test:cov']
run = "uv run pytest --cov -v"

[tasks.lint]
run = "uv run ruff check --fix ."

[tasks.format]
run = "uv run ruff format ."

[tasks.typecheck]
run = "uv run mypy ."

[tasks.tox]
description = "Run tests in multiple environments using tox"
run = "uv run tox"

[tasks.all]
depends = ["format", "lint", "typecheck", "tox", "test:cov"]

[tasks.clean]
description = "Clean up build artifacts and temporary files"
run = [
  "rm -rf .venv",
  "rm -rf __pycache__ **/__pycache__",
  "rm -rf .mypy_cache",
  "rm -rf .ruff_cache",
  "rm -rf .tox",
  "rm -rf .coverage",
  "rm -rf .pytest_cache",
]


[tasks.install]
description = "Install script"
run = ["cp otp-cli.py ~/.local/bin/otp-cli", "chmod +x ~/.local/bin/otp-cli"]
